### ISSUE TITLE
Screen Layout Pics?

### ISSUE THREAD

**Issue by MardellK** [delwinbest/MKS-TFT28_v4.0#1]
First time here. What advantages are there to your updates and is there screenshots you can add to the readme that describe this firmware change?

**Comment by delwinbest** [comment]
Hi MardellK - I need to make it very clear that right now, there is  NO advantage to using my code. It is very very far from usable. 
I accidentally erased my MKS TFT28 v4.0 board by resetting the code protection/code download prevention bit. MKS does not release any of their bootloader code nor is there anything else to replace it with on the internet. Meaning the board is now useless - except for developing something new. 

If you try load any other firmware other than what MKS provides you on the SDCARD, you will most likely brick the board. 

I hope to, in the future, get this code to a point where it runs the BIGTREEETECH TFT UI, maybe even allowing you to recover and run the MKS firmware. 

I've updated the readme with some of these notes.
